### ISSUE TITLE
Fix: 알람 로직 오류 수정

### ISSUE THREAD

**Issue by yaewonLee** [Wake-up-together-TogetUp/Togetup-iOS-Refactoring#45]
## To-do

- [x] 개인 알람 목록 정렬 오류 수정
- [x] 일회성 알람이 한 번에 비활성화 되는 오류 수정
- [x]  직접 등록 미션일 때 알람이 수정안되는 오류 수정
- [x] 미션 수행 후 아바타 new 라벨 반영
- [x] 그룹 알람일 때 팝업 로직 추가
